# Generated by Django 3.2.6 on 2021-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_number',
            field=models.CharField(default='08112021', max_length=50, verbose_name='Tracking Number'),
        ),
    ]
