# Generated by Django 3.2.6 on 2021-11-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_transaction_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_number',
            field=models.CharField(default='11042021', max_length=50, verbose_name='Tracking Number'),
        ),
    ]
