# Generated by Django 3.2.13 on 2022-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_transaction_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_number',
            field=models.CharField(default='05282022', max_length=50, verbose_name='Tracking Number'),
        ),
    ]
